create sequence if not exists public.order_number_seq start 1;
create sequence if not exists public.invoice_number_seq start 1;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null default ('EO-ORD-' || lpad(nextval('public.order_number_seq')::text, 5, '0')),
  customer jsonb not null,
  items jsonb not null,
  shipping_amount numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  payment_status text not null default 'pending',
  invoice_id text unique,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

alter table public.orders enable row level security;

create or replace function public.mark_order_paid_and_invoice(p_order_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invoice_id text;
begin
  select invoice_id into v_invoice_id
  from public.orders
  where order_id = p_order_id
  for update;

  if not found then
    raise exception 'Order not found';
  end if;

  if v_invoice_id is null then
    v_invoice_id := 'EO-INV-' || lpad(nextval('public.invoice_number_seq')::text, 5, '0');

    update public.orders
    set payment_status = 'paid',
        invoice_id = v_invoice_id,
        paid_at = now()
    where order_id = p_order_id;
  end if;

  return jsonb_build_object('invoice_id', v_invoice_id);
end;
$$;
